services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    expose:
      - "9001"
    restart: always
    environment:
      - TZ=Asia/Seoul
    networks:
      - app-tier
    volumes:
      - ./nginx/metrics.conf:/etc/nginx/conf.d/metrics.conf
      - ./nginx/logs:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/service-url.inc:/etc/nginx/service-url.inc
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    restart: always
    command: ["-nginx.scrape-uri","http://nginx:9001/stub_status"]
    expose:
      - "9113"
    networks:
      - app-tier
    depends_on:
      - nginx

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-tier:
    external: true
    name: docker_app-tier
